version: '3'
services:
  myapp:
    image: ubuntu:latest
    container_name: myapp_container
    volumes:
      - .:/app  # Mapeia o diretório local para dentro do contêiner (opcional)
    tty: true

    # Comandos para executar dentro do contêiner
    command: >
      bash -c "
      apt-get update && apt-get install -y curl python3 python3-pip &&
      curl -sSL https://install.python-poetry.org | python3 - &&
      poetry --version
      "
