name: Build and Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python 3.8
      uses: actions/setup-python@v4
      with:
        python-version: 3.8

    - name: Install Poetry
      run: |
        curl -sSL https://install.python-poetry.org | python3 -
      shell: bash

    - name: Install project dependencies
      run: |
        poetry install
      working-directory: .

    - name: Run make ci
      run: |
        make ci
      working-directory: ./tic-tac-toe-master
